
#ifndef MITKPLANARFIGURE_EXPORT_H
#define MITKPLANARFIGURE_EXPORT_H

#ifdef MITKPLANARFIGURE_STATIC_DEFINE
#  define MITKPLANARFIGURE_EXPORT
#  define MITKPLANARFIGURE_NO_EXPORT
#else
#  ifndef MITKPLANARFIGURE_EXPORT
#    ifdef MitkPlanarFigure_EXPORTS
        /* We are building this library */
#      define MITKPLANARFIGURE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKPLANARFIGURE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKPLANARFIGURE_NO_EXPORT
#    define MITKPLANARFIGURE_NO_EXPORT 
#  endif
#endif

#ifndef MITKPLANARFIGURE_DEPRECATED
#  define MITKPLANARFIGURE_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKPLANARFIGURE_DEPRECATED_EXPORT
#  define MITKPLANARFIGURE_DEPRECATED_EXPORT MITKPLANARFIGURE_EXPORT MITKPLANARFIGURE_DEPRECATED
#endif

#ifndef MITKPLANARFIGURE_DEPRECATED_NO_EXPORT
#  define MITKPLANARFIGURE_DEPRECATED_NO_EXPORT MITKPLANARFIGURE_NO_EXPORT MITKPLANARFIGURE_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKPLANARFIGURE_NO_DEPRECATED
#endif

#endif
