
#ifndef MITKDEFORMABLEREGISTRATION_EXPORT_H
#define MITKDEFORMABLEREGISTRATION_EXPORT_H

#ifdef MITKDEFORMABLEREGISTRATION_STATIC_DEFINE
#  define MITKDEFORMABLEREGISTRATION_EXPORT
#  define MITKDEFORMABLEREGISTRATION_NO_EXPORT
#else
#  ifndef MITKDEFORMABLEREGISTRATION_EXPORT
#    ifdef MitkDeformableRegistration_EXPORTS
        /* We are building this library */
#      define MITKDEFORMABLEREGISTRATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKDEFORMABLEREGISTRATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKDEFORMABLEREGISTRATION_NO_EXPORT
#    define MITKDEFORMABLEREGISTRATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKDEFORMABLEREGISTRATION_DEPRECATED
#  define MITKDEFORMABLEREGISTRATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKDEFORMABLEREGISTRATION_DEPRECATED_EXPORT
#  define MITKDEFORMABLEREGISTRATION_DEPRECATED_EXPORT MITKDEFORMABLEREGISTRATION_EXPORT MITKDEFORMABLEREGISTRATION_DEPRECATED
#endif

#ifndef MITKDEFORMABLEREGISTRATION_DEPRECATED_NO_EXPORT
#  define MITKDEFORMABLEREGISTRATION_DEPRECATED_NO_EXPORT MITKDEFORMABLEREGISTRATION_NO_EXPORT MITKDEFORMABLEREGISTRATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKDEFORMABLEREGISTRATION_NO_DEPRECATED
#endif

#endif
