
#ifndef MITKDIFFUSIONCORE_EXPORT_H
#define MITKDIFFUSIONCORE_EXPORT_H

#ifdef MITKDIFFUSIONCORE_STATIC_DEFINE
#  define MITKDIFFUSIONCORE_EXPORT
#  define MITKDIFFUSIONCORE_NO_EXPORT
#else
#  ifndef MITKDIFFUSIONCORE_EXPORT
#    ifdef MitkDiffusionCore_EXPORTS
        /* We are building this library */
#      define MITKDIFFUSIONCORE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKDIFFUSIONCORE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKDIFFUSIONCORE_NO_EXPORT
#    define MITKDIFFUSIONCORE_NO_EXPORT 
#  endif
#endif

#ifndef MITKDIFFUSIONCORE_DEPRECATED
#  define MITKDIFFUSIONCORE_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKDIFFUSIONCORE_DEPRECATED_EXPORT
#  define MITKDIFFUSIONCORE_DEPRECATED_EXPORT MITKDIFFUSIONCORE_EXPORT MITKDIFFUSIONCORE_DEPRECATED
#endif

#ifndef MITKDIFFUSIONCORE_DEPRECATED_NO_EXPORT
#  define MITKDIFFUSIONCORE_DEPRECATED_NO_EXPORT MITKDIFFUSIONCORE_NO_EXPORT MITKDIFFUSIONCORE_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKDIFFUSIONCORE_NO_DEPRECATED
#endif

#endif
