
#ifndef MITKALGORITHMSEXT_EXPORT_H
#define MITKALGORITHMSEXT_EXPORT_H

#ifdef MITKALGORITHMSEXT_STATIC_DEFINE
#  define MITKALGORITHMSEXT_EXPORT
#  define MITKALGORITHMSEXT_NO_EXPORT
#else
#  ifndef MITKALGORITHMSEXT_EXPORT
#    ifdef MitkAlgorithmsExt_EXPORTS
        /* We are building this library */
#      define MITKALGORITHMSEXT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKALGORITHMSEXT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKALGORITHMSEXT_NO_EXPORT
#    define MITKALGORITHMSEXT_NO_EXPORT 
#  endif
#endif

#ifndef MITKALGORITHMSEXT_DEPRECATED
#  define MITKALGORITHMSEXT_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKALGORITHMSEXT_DEPRECATED_EXPORT
#  define MITKALGORITHMSEXT_DEPRECATED_EXPORT MITKALGORITHMSEXT_EXPORT MITKALGORITHMSEXT_DEPRECATED
#endif

#ifndef MITKALGORITHMSEXT_DEPRECATED_NO_EXPORT
#  define MITKALGORITHMSEXT_DEPRECATED_NO_EXPORT MITKALGORITHMSEXT_NO_EXPORT MITKALGORITHMSEXT_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKALGORITHMSEXT_NO_DEPRECATED
#endif

#endif
