
#ifndef MITKRIGIDREGISTRATIONUI_EXPORT_H
#define MITKRIGIDREGISTRATIONUI_EXPORT_H

#ifdef MITKRIGIDREGISTRATIONUI_STATIC_DEFINE
#  define MITKRIGIDREGISTRATIONUI_EXPORT
#  define MITKRIGIDREGISTRATIONUI_NO_EXPORT
#else
#  ifndef MITKRIGIDREGISTRATIONUI_EXPORT
#    ifdef MitkRigidRegistrationUI_EXPORTS
        /* We are building this library */
#      define MITKRIGIDREGISTRATIONUI_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKRIGIDREGISTRATIONUI_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKRIGIDREGISTRATIONUI_NO_EXPORT
#    define MITKRIGIDREGISTRATIONUI_NO_EXPORT 
#  endif
#endif

#ifndef MITKRIGIDREGISTRATIONUI_DEPRECATED
#  define MITKRIGIDREGISTRATIONUI_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKRIGIDREGISTRATIONUI_DEPRECATED_EXPORT
#  define MITKRIGIDREGISTRATIONUI_DEPRECATED_EXPORT MITKRIGIDREGISTRATIONUI_EXPORT MITKRIGIDREGISTRATIONUI_DEPRECATED
#endif

#ifndef MITKRIGIDREGISTRATIONUI_DEPRECATED_NO_EXPORT
#  define MITKRIGIDREGISTRATIONUI_DEPRECATED_NO_EXPORT MITKRIGIDREGISTRATIONUI_NO_EXPORT MITKRIGIDREGISTRATIONUI_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKRIGIDREGISTRATIONUI_NO_DEPRECATED
#endif

#endif
