# Generated by CMake 3.5.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget CTKCore CTKPluginFramework CTKWidgets CTKDICOMCore CTKDICOMWidgets CTKCommandLineModulesCore CTKCommandLineModulesFrontendQtGui CTKCommandLineModulesBackendLocalProcess CTKXNATCore org_commontk_configadmin org_commontk_eventadmin)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target CTKCore
add_library(CTKCore SHARED IMPORTED)

# Create imported target CTKPluginFramework
add_library(CTKPluginFramework SHARED IMPORTED)

# Create imported target CTKWidgets
add_library(CTKWidgets SHARED IMPORTED)

# Create imported target CTKDICOMCore
add_library(CTKDICOMCore SHARED IMPORTED)

# Create imported target CTKDICOMWidgets
add_library(CTKDICOMWidgets SHARED IMPORTED)

# Create imported target CTKCommandLineModulesCore
add_library(CTKCommandLineModulesCore SHARED IMPORTED)

# Create imported target CTKCommandLineModulesFrontendQtGui
add_library(CTKCommandLineModulesFrontendQtGui SHARED IMPORTED)

# Create imported target CTKCommandLineModulesBackendLocalProcess
add_library(CTKCommandLineModulesBackendLocalProcess SHARED IMPORTED)

# Create imported target CTKXNATCore
add_library(CTKXNATCore SHARED IMPORTED)

# Create imported target org_commontk_configadmin
add_library(org_commontk_configadmin SHARED IMPORTED)

set_target_properties(org_commontk_configadmin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "E:/D/MITK-superbuild/ep/src/CTK/Plugins/org.commontk.configadmin;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/Plugins/org.commontk.configadmin;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build;E:/D/MITK-superbuild/ep/src/CTK/Libs/PluginFramework;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/Libs/PluginFramework;E:/D/MITK-superbuild/ep/src/CTK/Libs/Core;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/Libs/Core"
)

# Create imported target org_commontk_eventadmin
add_library(org_commontk_eventadmin SHARED IMPORTED)

set_target_properties(org_commontk_eventadmin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "E:/D/MITK-superbuild/ep/src/CTK/Plugins/org.commontk.eventadmin;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/Plugins/org.commontk.eventadmin;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build;E:/D/MITK-superbuild/ep/src/CTK/Libs/PluginFramework;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/Libs/PluginFramework;E:/D/MITK-superbuild/ep/src/CTK/Libs/Core;E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/Libs/Core"
)

# Import target "CTKCore" for configuration "Debug"
set_property(TARGET CTKCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKCore PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Qt5::Core;dbghelp"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCore.dll"
  )

# Import target "CTKPluginFramework" for configuration "Debug"
set_property(TARGET CTKPluginFramework APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKPluginFramework PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKPluginFramework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCore;Qt5::Sql;Qt5::Concurrent"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKPluginFramework.dll"
  )

# Import target "CTKWidgets" for configuration "Debug"
set_property(TARGET CTKWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKWidgets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCore;Qt5::Widgets;Qt5::Xml;Qt5::OpenGL"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKWidgets.dll"
  )

# Import target "CTKDICOMCore" for configuration "Debug"
set_property(TARGET CTKDICOMCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKDICOMCore PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKDICOMCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCore;E:/D/MITK-superbuild/ep/lib/dcmpstatd.lib;E:/D/MITK-superbuild/ep/lib/dcmsrd.lib;E:/D/MITK-superbuild/ep/lib/dcmtlsd.lib;E:/D/MITK-superbuild/ep/lib/dcmqrdbd.lib;E:/D/MITK-superbuild/ep/lib/dcmnetd.lib;E:/D/MITK-superbuild/ep/lib/dcmjpegd.lib;E:/D/MITK-superbuild/ep/lib/dcmimaged.lib;E:/D/MITK-superbuild/ep/lib/dcmimgled.lib;E:/D/MITK-superbuild/ep/lib/dcmdatad.lib;E:/D/MITK-superbuild/ep/lib/oflogd.lib;E:/D/MITK-superbuild/ep/lib/ofstdd.lib;E:/D/MITK-superbuild/ep/lib/ijg12d.lib;E:/D/MITK-superbuild/ep/lib/ijg16d.lib;E:/D/MITK-superbuild/ep/lib/ijg8d.lib;netapi32;wsock32;Qt5::Sql;Qt5::Gui"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKDICOMCore.dll"
  )

# Import target "CTKDICOMWidgets" for configuration "Debug"
set_property(TARGET CTKDICOMWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKDICOMWidgets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKDICOMWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKDICOMCore;CTKWidgets"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKDICOMWidgets.dll"
  )

# Import target "CTKCommandLineModulesCore" for configuration "Debug"
set_property(TARGET CTKCommandLineModulesCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKCommandLineModulesCore PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCommandLineModulesCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCore;Qt5::XmlPatterns;Qt5::Widgets;Qt5::Concurrent"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCommandLineModulesCore.dll"
  )

# Import target "CTKCommandLineModulesFrontendQtGui" for configuration "Debug"
set_property(TARGET CTKCommandLineModulesFrontendQtGui APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKCommandLineModulesFrontendQtGui PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCommandLineModulesFrontendQtGui.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCommandLineModulesCore;Qt5::UiTools;Qt5::Widgets"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCommandLineModulesFrontendQtGui.dll"
  )

# Import target "CTKCommandLineModulesBackendLocalProcess" for configuration "Debug"
set_property(TARGET CTKCommandLineModulesBackendLocalProcess APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKCommandLineModulesBackendLocalProcess PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCommandLineModulesBackendLocalProcess.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCommandLineModulesCore"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKCommandLineModulesBackendLocalProcess.dll"
  )

# Import target "CTKXNATCore" for configuration "Debug"
set_property(TARGET CTKXNATCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CTKXNATCore PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKXNATCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKCore;qRestAPI"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/CTKXNATCore.dll"
  )

# Import target "org_commontk_configadmin" for configuration "Debug"
set_property(TARGET org_commontk_configadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(org_commontk_configadmin PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/org_commontk_configadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKPluginFramework"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/liborg_commontk_configadmin.dll"
  )

# Import target "org_commontk_eventadmin" for configuration "Debug"
set_property(TARGET org_commontk_eventadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(org_commontk_eventadmin PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/org_commontk_eventadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "CTKPluginFramework"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Debug/liborg_commontk_eventadmin.dll"
  )

# Import target "CTKCore" for configuration "Release"
set_property(TARGET CTKCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKCore PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "Qt5::Core;dbghelp"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCore.dll"
  )

# Import target "CTKPluginFramework" for configuration "Release"
set_property(TARGET CTKPluginFramework APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKPluginFramework PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKPluginFramework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCore;Qt5::Sql;Qt5::Concurrent"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKPluginFramework.dll"
  )

# Import target "CTKWidgets" for configuration "Release"
set_property(TARGET CTKWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKWidgets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCore;Qt5::Widgets;Qt5::Xml;Qt5::OpenGL"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKWidgets.dll"
  )

# Import target "CTKDICOMCore" for configuration "Release"
set_property(TARGET CTKDICOMCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKDICOMCore PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKDICOMCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCore;netapi32;wsock32;Qt5::Sql;Qt5::Gui"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKDICOMCore.dll"
  )

# Import target "CTKDICOMWidgets" for configuration "Release"
set_property(TARGET CTKDICOMWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKDICOMWidgets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKDICOMWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKDICOMCore;CTKWidgets"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKDICOMWidgets.dll"
  )

# Import target "CTKCommandLineModulesCore" for configuration "Release"
set_property(TARGET CTKCommandLineModulesCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKCommandLineModulesCore PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCommandLineModulesCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCore;Qt5::XmlPatterns;Qt5::Widgets;Qt5::Concurrent"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCommandLineModulesCore.dll"
  )

# Import target "CTKCommandLineModulesFrontendQtGui" for configuration "Release"
set_property(TARGET CTKCommandLineModulesFrontendQtGui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKCommandLineModulesFrontendQtGui PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCommandLineModulesFrontendQtGui.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCommandLineModulesCore;Qt5::UiTools;Qt5::Widgets"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCommandLineModulesFrontendQtGui.dll"
  )

# Import target "CTKCommandLineModulesBackendLocalProcess" for configuration "Release"
set_property(TARGET CTKCommandLineModulesBackendLocalProcess APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKCommandLineModulesBackendLocalProcess PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCommandLineModulesBackendLocalProcess.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCommandLineModulesCore"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKCommandLineModulesBackendLocalProcess.dll"
  )

# Import target "CTKXNATCore" for configuration "Release"
set_property(TARGET CTKXNATCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CTKXNATCore PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKXNATCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKCore;qRestAPI"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/CTKXNATCore.dll"
  )

# Import target "org_commontk_configadmin" for configuration "Release"
set_property(TARGET org_commontk_configadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(org_commontk_configadmin PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/org_commontk_configadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKPluginFramework"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/liborg_commontk_configadmin.dll"
  )

# Import target "org_commontk_eventadmin" for configuration "Release"
set_property(TARGET org_commontk_eventadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(org_commontk_eventadmin PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/org_commontk_eventadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "CTKPluginFramework"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/Release/liborg_commontk_eventadmin.dll"
  )

# Import target "CTKCore" for configuration "MinSizeRel"
set_property(TARGET CTKCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKCore PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "Qt5::Core;dbghelp"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCore.dll"
  )

# Import target "CTKPluginFramework" for configuration "MinSizeRel"
set_property(TARGET CTKPluginFramework APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKPluginFramework PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKPluginFramework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCore;Qt5::Sql;Qt5::Concurrent"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKPluginFramework.dll"
  )

# Import target "CTKWidgets" for configuration "MinSizeRel"
set_property(TARGET CTKWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKWidgets PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCore;Qt5::Widgets;Qt5::Xml;Qt5::OpenGL"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKWidgets.dll"
  )

# Import target "CTKDICOMCore" for configuration "MinSizeRel"
set_property(TARGET CTKDICOMCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKDICOMCore PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKDICOMCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCore;netapi32;wsock32;Qt5::Sql;Qt5::Gui"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKDICOMCore.dll"
  )

# Import target "CTKDICOMWidgets" for configuration "MinSizeRel"
set_property(TARGET CTKDICOMWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKDICOMWidgets PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKDICOMWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKDICOMCore;CTKWidgets"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKDICOMWidgets.dll"
  )

# Import target "CTKCommandLineModulesCore" for configuration "MinSizeRel"
set_property(TARGET CTKCommandLineModulesCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKCommandLineModulesCore PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCommandLineModulesCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCore;Qt5::XmlPatterns;Qt5::Widgets;Qt5::Concurrent"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCommandLineModulesCore.dll"
  )

# Import target "CTKCommandLineModulesFrontendQtGui" for configuration "MinSizeRel"
set_property(TARGET CTKCommandLineModulesFrontendQtGui APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKCommandLineModulesFrontendQtGui PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCommandLineModulesFrontendQtGui.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCommandLineModulesCore;Qt5::UiTools;Qt5::Widgets"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCommandLineModulesFrontendQtGui.dll"
  )

# Import target "CTKCommandLineModulesBackendLocalProcess" for configuration "MinSizeRel"
set_property(TARGET CTKCommandLineModulesBackendLocalProcess APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKCommandLineModulesBackendLocalProcess PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCommandLineModulesBackendLocalProcess.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCommandLineModulesCore"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKCommandLineModulesBackendLocalProcess.dll"
  )

# Import target "CTKXNATCore" for configuration "MinSizeRel"
set_property(TARGET CTKXNATCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CTKXNATCore PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKXNATCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKCore;qRestAPI"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/CTKXNATCore.dll"
  )

# Import target "org_commontk_configadmin" for configuration "MinSizeRel"
set_property(TARGET org_commontk_configadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(org_commontk_configadmin PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/org_commontk_configadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKPluginFramework"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/liborg_commontk_configadmin.dll"
  )

# Import target "org_commontk_eventadmin" for configuration "MinSizeRel"
set_property(TARGET org_commontk_eventadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(org_commontk_eventadmin PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/org_commontk_eventadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "CTKPluginFramework"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/MinSizeRel/liborg_commontk_eventadmin.dll"
  )

# Import target "CTKCore" for configuration "RelWithDebInfo"
set_property(TARGET CTKCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKCore PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "Qt5::Core;dbghelp"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCore.dll"
  )

# Import target "CTKPluginFramework" for configuration "RelWithDebInfo"
set_property(TARGET CTKPluginFramework APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKPluginFramework PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKPluginFramework.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCore;Qt5::Sql;Qt5::Concurrent"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKPluginFramework.dll"
  )

# Import target "CTKWidgets" for configuration "RelWithDebInfo"
set_property(TARGET CTKWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKWidgets PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCore;Qt5::Widgets;Qt5::Xml;Qt5::OpenGL"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKWidgets.dll"
  )

# Import target "CTKDICOMCore" for configuration "RelWithDebInfo"
set_property(TARGET CTKDICOMCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKDICOMCore PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKDICOMCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCore;netapi32;wsock32;Qt5::Sql;Qt5::Gui"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKDICOMCore.dll"
  )

# Import target "CTKDICOMWidgets" for configuration "RelWithDebInfo"
set_property(TARGET CTKDICOMWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKDICOMWidgets PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKDICOMWidgets.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKDICOMCore;CTKWidgets"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKDICOMWidgets.dll"
  )

# Import target "CTKCommandLineModulesCore" for configuration "RelWithDebInfo"
set_property(TARGET CTKCommandLineModulesCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKCommandLineModulesCore PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCommandLineModulesCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCore;Qt5::XmlPatterns;Qt5::Widgets;Qt5::Concurrent"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCommandLineModulesCore.dll"
  )

# Import target "CTKCommandLineModulesFrontendQtGui" for configuration "RelWithDebInfo"
set_property(TARGET CTKCommandLineModulesFrontendQtGui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKCommandLineModulesFrontendQtGui PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCommandLineModulesFrontendQtGui.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCommandLineModulesCore;Qt5::UiTools;Qt5::Widgets"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCommandLineModulesFrontendQtGui.dll"
  )

# Import target "CTKCommandLineModulesBackendLocalProcess" for configuration "RelWithDebInfo"
set_property(TARGET CTKCommandLineModulesBackendLocalProcess APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKCommandLineModulesBackendLocalProcess PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCommandLineModulesBackendLocalProcess.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCommandLineModulesCore"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKCommandLineModulesBackendLocalProcess.dll"
  )

# Import target "CTKXNATCore" for configuration "RelWithDebInfo"
set_property(TARGET CTKXNATCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CTKXNATCore PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKXNATCore.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKCore;qRestAPI"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/CTKXNATCore.dll"
  )

# Import target "org_commontk_configadmin" for configuration "RelWithDebInfo"
set_property(TARGET org_commontk_configadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(org_commontk_configadmin PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/org_commontk_configadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKPluginFramework"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/liborg_commontk_configadmin.dll"
  )

# Import target "org_commontk_eventadmin" for configuration "RelWithDebInfo"
set_property(TARGET org_commontk_eventadmin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(org_commontk_eventadmin PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/org_commontk_eventadmin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "CTKPluginFramework"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/CTK-build/CTK-build/bin/RelWithDebInfo/liborg_commontk_eventadmin.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
