
#ifndef MITKDICOMREADER_EXPORT_H
#define MITKDICOMREADER_EXPORT_H

#ifdef MITKDICOMREADER_STATIC_DEFINE
#  define MITKDICOMREADER_EXPORT
#  define MITKDICOMREADER_NO_EXPORT
#else
#  ifndef MITKDICOMREADER_EXPORT
#    ifdef MitkDICOMReader_EXPORTS
        /* We are building this library */
#      define MITKDICOMREADER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKDICOMREADER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKDICOMREADER_NO_EXPORT
#    define MITKDICOMREADER_NO_EXPORT 
#  endif
#endif

#ifndef MITKDICOMREADER_DEPRECATED
#  define MITKDICOMREADER_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKDICOMREADER_DEPRECATED_EXPORT
#  define MITKDICOMREADER_DEPRECATED_EXPORT MITKDICOMREADER_EXPORT MITKDICOMREADER_DEPRECATED
#endif

#ifndef MITKDICOMREADER_DEPRECATED_NO_EXPORT
#  define MITKDICOMREADER_DEPRECATED_NO_EXPORT MITKDICOMREADER_NO_EXPORT MITKDICOMREADER_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKDICOMREADER_NO_DEPRECATED
#endif

#endif
