
#ifndef MITKCONTOURMODEL_EXPORT_H
#define MITKCONTOURMODEL_EXPORT_H

#ifdef MITKCONTOURMODEL_STATIC_DEFINE
#  define MITKCONTOURMODEL_EXPORT
#  define MITKCONTOURMODEL_NO_EXPORT
#else
#  ifndef MITKCONTOURMODEL_EXPORT
#    ifdef MitkContourModel_EXPORTS
        /* We are building this library */
#      define MITKCONTOURMODEL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKCONTOURMODEL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKCONTOURMODEL_NO_EXPORT
#    define MITKCONTOURMODEL_NO_EXPORT 
#  endif
#endif

#ifndef MITKCONTOURMODEL_DEPRECATED
#  define MITKCONTOURMODEL_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKCONTOURMODEL_DEPRECATED_EXPORT
#  define MITKCONTOURMODEL_DEPRECATED_EXPORT MITKCONTOURMODEL_EXPORT MITKCONTOURMODEL_DEPRECATED
#endif

#ifndef MITKCONTOURMODEL_DEPRECATED_NO_EXPORT
#  define MITKCONTOURMODEL_DEPRECATED_NO_EXPORT MITKCONTOURMODEL_NO_EXPORT MITKCONTOURMODEL_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKCONTOURMODEL_NO_DEPRECATED
#endif

#endif
