
#ifndef MITKTESTINGHELPER_EXPORT_H
#define MITKTESTINGHELPER_EXPORT_H

#ifdef MITKTESTINGHELPER_STATIC_DEFINE
#  define MITKTESTINGHELPER_EXPORT
#  define MITKTESTINGHELPER_NO_EXPORT
#else
#  ifndef MITKTESTINGHELPER_EXPORT
#    ifdef MitkTestingHelper_EXPORTS
        /* We are building this library */
#      define MITKTESTINGHELPER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKTESTINGHELPER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKTESTINGHELPER_NO_EXPORT
#    define MITKTESTINGHELPER_NO_EXPORT 
#  endif
#endif

#ifndef MITKTESTINGHELPER_DEPRECATED
#  define MITKTESTINGHELPER_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKTESTINGHELPER_DEPRECATED_EXPORT
#  define MITKTESTINGHELPER_DEPRECATED_EXPORT MITKTESTINGHELPER_EXPORT MITKTESTINGHELPER_DEPRECATED
#endif

#ifndef MITKTESTINGHELPER_DEPRECATED_NO_EXPORT
#  define MITKTESTINGHELPER_DEPRECATED_NO_EXPORT MITKTESTINGHELPER_NO_EXPORT MITKTESTINGHELPER_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKTESTINGHELPER_NO_DEPRECATED
#endif

#endif
