
#ifndef MITKDATATYPESEXT_EXPORT_H
#define MITKDATATYPESEXT_EXPORT_H

#ifdef MITKDATATYPESEXT_STATIC_DEFINE
#  define MITKDATATYPESEXT_EXPORT
#  define MITKDATATYPESEXT_NO_EXPORT
#else
#  ifndef MITKDATATYPESEXT_EXPORT
#    ifdef MitkDataTypesExt_EXPORTS
        /* We are building this library */
#      define MITKDATATYPESEXT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKDATATYPESEXT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKDATATYPESEXT_NO_EXPORT
#    define MITKDATATYPESEXT_NO_EXPORT 
#  endif
#endif

#ifndef MITKDATATYPESEXT_DEPRECATED
#  define MITKDATATYPESEXT_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKDATATYPESEXT_DEPRECATED_EXPORT
#  define MITKDATATYPESEXT_DEPRECATED_EXPORT MITKDATATYPESEXT_EXPORT MITKDATATYPESEXT_DEPRECATED
#endif

#ifndef MITKDATATYPESEXT_DEPRECATED_NO_EXPORT
#  define MITKDATATYPESEXT_DEPRECATED_NO_EXPORT MITKDATATYPESEXT_NO_EXPORT MITKDATATYPESEXT_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKDATATYPESEXT_NO_DEPRECATED
#endif

#endif
