
#ifndef MITKQTWIDGETSEXT_EXPORT_H
#define MITKQTWIDGETSEXT_EXPORT_H

#ifdef MITKQTWIDGETSEXT_STATIC_DEFINE
#  define MITKQTWIDGETSEXT_EXPORT
#  define MITKQTWIDGETSEXT_NO_EXPORT
#else
#  ifndef MITKQTWIDGETSEXT_EXPORT
#    ifdef MitkQtWidgetsExt_EXPORTS
        /* We are building this library */
#      define MITKQTWIDGETSEXT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKQTWIDGETSEXT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKQTWIDGETSEXT_NO_EXPORT
#    define MITKQTWIDGETSEXT_NO_EXPORT 
#  endif
#endif

#ifndef MITKQTWIDGETSEXT_DEPRECATED
#  define MITKQTWIDGETSEXT_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKQTWIDGETSEXT_DEPRECATED_EXPORT
#  define MITKQTWIDGETSEXT_DEPRECATED_EXPORT MITKQTWIDGETSEXT_EXPORT MITKQTWIDGETSEXT_DEPRECATED
#endif

#ifndef MITKQTWIDGETSEXT_DEPRECATED_NO_EXPORT
#  define MITKQTWIDGETSEXT_DEPRECATED_NO_EXPORT MITKQTWIDGETSEXT_NO_EXPORT MITKQTWIDGETSEXT_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKQTWIDGETSEXT_NO_DEPRECATED
#endif

#endif
