
#ifndef MITKSEGMENTATION_EXPORT_H
#define MITKSEGMENTATION_EXPORT_H

#ifdef MITKSEGMENTATION_STATIC_DEFINE
#  define MITKSEGMENTATION_EXPORT
#  define MITKSEGMENTATION_NO_EXPORT
#else
#  ifndef MITKSEGMENTATION_EXPORT
#    ifdef MitkSegmentation_EXPORTS
        /* We are building this library */
#      define MITKSEGMENTATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKSEGMENTATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKSEGMENTATION_NO_EXPORT
#    define MITKSEGMENTATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKSEGMENTATION_DEPRECATED
#  define MITKSEGMENTATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKSEGMENTATION_DEPRECATED_EXPORT
#  define MITKSEGMENTATION_DEPRECATED_EXPORT MITKSEGMENTATION_EXPORT MITKSEGMENTATION_DEPRECATED
#endif

#ifndef MITKSEGMENTATION_DEPRECATED_NO_EXPORT
#  define MITKSEGMENTATION_DEPRECATED_NO_EXPORT MITKSEGMENTATION_NO_EXPORT MITKSEGMENTATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKSEGMENTATION_NO_DEPRECATED
#endif

#endif
