
#ifndef MITKIPSEGMENTATION_EXPORT_H
#define MITKIPSEGMENTATION_EXPORT_H

#ifdef MITKIPSEGMENTATION_STATIC_DEFINE
#  define MITKIPSEGMENTATION_EXPORT
#  define MITKIPSEGMENTATION_NO_EXPORT
#else
#  ifndef MITKIPSEGMENTATION_EXPORT
#    ifdef MitkIpSegmentation_EXPORTS
        /* We are building this library */
#      define MITKIPSEGMENTATION_EXPORT 
#    else
        /* We are using this library */
#      define MITKIPSEGMENTATION_EXPORT 
#    endif
#  endif

#  ifndef MITKIPSEGMENTATION_NO_EXPORT
#    define MITKIPSEGMENTATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKIPSEGMENTATION_DEPRECATED
#  define MITKIPSEGMENTATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKIPSEGMENTATION_DEPRECATED_EXPORT
#  define MITKIPSEGMENTATION_DEPRECATED_EXPORT MITKIPSEGMENTATION_EXPORT MITKIPSEGMENTATION_DEPRECATED
#endif

#ifndef MITKIPSEGMENTATION_DEPRECATED_NO_EXPORT
#  define MITKIPSEGMENTATION_DEPRECATED_NO_EXPORT MITKIPSEGMENTATION_NO_EXPORT MITKIPSEGMENTATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKIPSEGMENTATION_NO_DEPRECATED
#endif

#endif
