
#ifndef MITKSURFACEINTERPOLATION_EXPORT_H
#define MITKSURFACEINTERPOLATION_EXPORT_H

#ifdef MITKSURFACEINTERPOLATION_STATIC_DEFINE
#  define MITKSURFACEINTERPOLATION_EXPORT
#  define MITKSURFACEINTERPOLATION_NO_EXPORT
#else
#  ifndef MITKSURFACEINTERPOLATION_EXPORT
#    ifdef MitkSurfaceInterpolation_EXPORTS
        /* We are building this library */
#      define MITKSURFACEINTERPOLATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKSURFACEINTERPOLATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKSURFACEINTERPOLATION_NO_EXPORT
#    define MITKSURFACEINTERPOLATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKSURFACEINTERPOLATION_DEPRECATED
#  define MITKSURFACEINTERPOLATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKSURFACEINTERPOLATION_DEPRECATED_EXPORT
#  define MITKSURFACEINTERPOLATION_DEPRECATED_EXPORT MITKSURFACEINTERPOLATION_EXPORT MITKSURFACEINTERPOLATION_DEPRECATED
#endif

#ifndef MITKSURFACEINTERPOLATION_DEPRECATED_NO_EXPORT
#  define MITKSURFACEINTERPOLATION_DEPRECATED_NO_EXPORT MITKSURFACEINTERPOLATION_NO_EXPORT MITKSURFACEINTERPOLATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKSURFACEINTERPOLATION_NO_DEPRECATED
#endif

#endif
