
#ifndef MITKSEGMENTATIONUI_EXPORT_H
#define MITKSEGMENTATIONUI_EXPORT_H

#ifdef MITKSEGMENTATIONUI_STATIC_DEFINE
#  define MITKSEGMENTATIONUI_EXPORT
#  define MITKSEGMENTATIONUI_NO_EXPORT
#else
#  ifndef MITKSEGMENTATIONUI_EXPORT
#    ifdef MitkSegmentationUI_EXPORTS
        /* We are building this library */
#      define MITKSEGMENTATIONUI_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKSEGMENTATIONUI_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKSEGMENTATIONUI_NO_EXPORT
#    define MITKSEGMENTATIONUI_NO_EXPORT 
#  endif
#endif

#ifndef MITKSEGMENTATIONUI_DEPRECATED
#  define MITKSEGMENTATIONUI_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKSEGMENTATIONUI_DEPRECATED_EXPORT
#  define MITKSEGMENTATIONUI_DEPRECATED_EXPORT MITKSEGMENTATIONUI_EXPORT MITKSEGMENTATIONUI_DEPRECATED
#endif

#ifndef MITKSEGMENTATIONUI_DEPRECATED_NO_EXPORT
#  define MITKSEGMENTATIONUI_DEPRECATED_NO_EXPORT MITKSEGMENTATIONUI_NO_EXPORT MITKSEGMENTATIONUI_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKSEGMENTATIONUI_NO_DEPRECATED
#endif

#endif
