set(vtkCommonCore_LOADED 1)
set(vtkCommonCore_DEPENDS "vtksys")
set(vtkCommonCore_LIBRARIES "vtkCommonCore")
set(vtkCommonCore_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/VTK-build/Common/Core;E:/D/MITK-superbuild/ep/src/VTK/Common/Core")
set(vtkCommonCore_LIBRARY_DIRS "")
set(vtkCommonCore_RUNTIME_LIBRARY_DIRS "E:/D/MITK-superbuild/ep/src/VTK-build/bin")
set(vtkCommonCore_WRAP_HIERARCHY_FILE "")
set(VTK_DEBUG_LEAKS "OFF")
set(VTK_USE_64BIT_IDS "OFF")
set(VTK_ALL_NEW_OBJECT_FACTORY "OFF")

