/*
  mitToFPMDConfig.h
  the file mitToFPMDConfig.h is generated. Do not change!
*/

#define MITK_TOF_PMDCAMBOARD_SOURCE_PLUGIN ""
#define MITK_TOF_PMDCAMBOARD_PROCESSING_PLUGIN ""
#define MITK_TOF_PMDO3_SOURCE_PLUGIN ""
#define MITK_TOF_PMDO3_PROCESSING_PLUGIN ""
#define MITK_TOF_PMDFILE_SOURCE_PLUGIN ""
#define MITK_TOF_PMDCAMCUBE_SOURCE_PLUGIN ""
#define MITK_TOF_PMDCAMCUBE_PROCESSING_PLUGIN ""
/* #undef MITK_USE_TOF_PMDCAMCUBE */
/* #undef MITK_USE_TOF_PMDCAMBOARD */
/* #undef MITK_USE_TOF_PMDO3 */
