
#ifndef MITKSCENESERIALIZATION_EXPORT_H
#define MITKSCENESERIALIZATION_EXPORT_H

#ifdef MITKSCENESERIALIZATION_STATIC_DEFINE
#  define MITKSCENESERIALIZATION_EXPORT
#  define MITKSCENESERIALIZATION_NO_EXPORT
#else
#  ifndef MITKSCENESERIALIZATION_EXPORT
#    ifdef MitkSceneSerialization_EXPORTS
        /* We are building this library */
#      define MITKSCENESERIALIZATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKSCENESERIALIZATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKSCENESERIALIZATION_NO_EXPORT
#    define MITKSCENESERIALIZATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKSCENESERIALIZATION_DEPRECATED
#  define MITKSCENESERIALIZATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKSCENESERIALIZATION_DEPRECATED_EXPORT
#  define MITKSCENESERIALIZATION_DEPRECATED_EXPORT MITKSCENESERIALIZATION_EXPORT MITKSCENESERIALIZATION_DEPRECATED
#endif

#ifndef MITKSCENESERIALIZATION_DEPRECATED_NO_EXPORT
#  define MITKSCENESERIALIZATION_DEPRECATED_NO_EXPORT MITKSCENESERIALIZATION_NO_EXPORT MITKSCENESERIALIZATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKSCENESERIALIZATION_NO_DEPRECATED
#endif

#endif
