set(ITKGIFTI_LOADED 1)
set(ITKGIFTI_DEPENDS "ITKExpat;ITKNIFTI;ITKZLIB")
set(ITKGIFTI_LIBRARIES "ITKgiftiio")
set(ITKGIFTI_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/ThirdParty/GIFTI/src/gifticlib")
set(ITKGIFTI_LIBRARY_DIRS "")

