set(ITKIOPNG_LOADED 1)
set(ITKIOPNG_DEPENDS "ITKIOImageBase;ITKPNG")
set(ITKIOPNG_LIBRARIES "ITKIOPNG")
set(ITKIOPNG_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/PNG/include")
set(ITKIOPNG_LIBRARY_DIRS "")

