set(ITKIOHDF5_LOADED 1)
set(ITKIOHDF5_DEPENDS "ITKCommon;ITKHDF5;ITKIOImageBase")
set(ITKIOHDF5_LIBRARIES "ITKIOHDF5")
set(ITKIOHDF5_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/HDF5/include")
set(ITKIOHDF5_LIBRARY_DIRS "")

