set(ITKIOBMP_LOADED 1)
set(ITKIOBMP_DEPENDS "ITKIOImageBase")
set(ITKIOBMP_LIBRARIES "ITKIOBMP")
set(ITKIOBMP_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/BMP/include")
set(ITKIOBMP_LIBRARY_DIRS "")

