set(ITKIOXML_LOADED 1)
set(ITKIOXML_DEPENDS "ITKExpat;ITKIOImageBase")
set(ITKIOXML_LIBRARIES "ITKIOXML")
set(ITKIOXML_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/XML/include")
set(ITKIOXML_LIBRARY_DIRS "")

