set(ITKIOTIFF_LOADED 1)
set(ITKIOTIFF_DEPENDS "ITKIOImageBase;ITKTIFF")
set(ITKIOTIFF_LIBRARIES "ITKIOTIFF")
set(ITKIOTIFF_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/TIFF/include")
set(ITKIOTIFF_LIBRARY_DIRS "")

