set(ITKIOCSV_LOADED 1)
set(ITKIOCSV_DEPENDS "ITKIOImageBase")
set(ITKIOCSV_LIBRARIES "ITKIOCSV")
set(ITKIOCSV_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/CSV/include")
set(ITKIOCSV_LIBRARY_DIRS "")

