set(ITKIOVTK_LOADED 1)
set(ITKIOVTK_DEPENDS "ITKIOImageBase")
set(ITKIOVTK_LIBRARIES "ITKIOVTK")
set(ITKIOVTK_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/VTK/include")
set(ITKIOVTK_LIBRARY_DIRS "")

