set(ITKIONIFTI_LOADED 1)
set(ITKIONIFTI_DEPENDS "ITKIOImageBase;ITKNIFTI")
set(ITKIONIFTI_LIBRARIES "ITKIONIFTI")
set(ITKIONIFTI_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/NIFTI/include")
set(ITKIONIFTI_LIBRARY_DIRS "")

