set(ITKIONRRD_LOADED 1)
set(ITKIONRRD_DEPENDS "ITKIOImageBase;ITKNrrdIO")
set(ITKIONRRD_LIBRARIES "ITKIONRRD")
set(ITKIONRRD_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/NRRD/include")
set(ITKIONRRD_LIBRARY_DIRS "")

