set(ITKIOGIPL_LOADED 1)
set(ITKIOGIPL_DEPENDS "ITKIOImageBase;ITKZLIB")
set(ITKIOGIPL_LIBRARIES "ITKIOGIPL")
set(ITKIOGIPL_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/GIPL/include")
set(ITKIOGIPL_LIBRARY_DIRS "")

