set(ITKIOLSM_LOADED 1)
set(ITKIOLSM_DEPENDS "ITKIOTIFF")
set(ITKIOLSM_LIBRARIES "ITKIOLSM")
set(ITKIOLSM_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/IO/LSM/include")
set(ITKIOLSM_LIBRARY_DIRS "")

