set(ITKTestKernel_LOADED 1)
set(ITKTestKernel_DEPENDS "ITKDoubleConversion;ITKIOBMP;ITKIOBioRad;ITKIOGDCM;ITKIOGIPL;ITKIOJPEG;ITKIOLSM;ITKIOMeta;ITKIONIFTI;ITKIONRRD;ITKIOPNG;ITKIOStimulate;ITKIOTIFF;ITKIOVTK;ITKKWSys")
set(ITKTestKernel_LIBRARIES "itkdouble-conversion;ITKIOBMP;ITKIOBioRad;ITKIOGDCM;ITKIOGIPL;ITKIOJPEG;ITKIOLSM;ITKIOMeta;ITKIONIFTI;ITKIONRRD;ITKIOPNG;ITKIOStimulate;ITKIOTIFF;ITKIOVTK;itksys")
set(ITKTestKernel_INCLUDE_DIRS "E:/D/MITK-superbuild/ep/src/ITK/Modules/Core/TestKernel/include")
set(ITKTestKernel_LIBRARY_DIRS "")

