
#ifndef MITKIMAGESTATISTICS_EXPORT_H
#define MITKIMAGESTATISTICS_EXPORT_H

#ifdef MITKIMAGESTATISTICS_STATIC_DEFINE
#  define MITKIMAGESTATISTICS_EXPORT
#  define MITKIMAGESTATISTICS_NO_EXPORT
#else
#  ifndef MITKIMAGESTATISTICS_EXPORT
#    ifdef MitkImageStatistics_EXPORTS
        /* We are building this library */
#      define MITKIMAGESTATISTICS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKIMAGESTATISTICS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKIMAGESTATISTICS_NO_EXPORT
#    define MITKIMAGESTATISTICS_NO_EXPORT 
#  endif
#endif

#ifndef MITKIMAGESTATISTICS_DEPRECATED
#  define MITKIMAGESTATISTICS_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKIMAGESTATISTICS_DEPRECATED_EXPORT
#  define MITKIMAGESTATISTICS_DEPRECATED_EXPORT MITKIMAGESTATISTICS_EXPORT MITKIMAGESTATISTICS_DEPRECATED
#endif

#ifndef MITKIMAGESTATISTICS_DEPRECATED_NO_EXPORT
#  define MITKIMAGESTATISTICS_DEPRECATED_NO_EXPORT MITKIMAGESTATISTICS_NO_EXPORT MITKIMAGESTATISTICS_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKIMAGESTATISTICS_NO_DEPRECATED
#endif

#endif
