
#ifndef MITKPLANARFIGURESEGMENTATION_EXPORT_H
#define MITKPLANARFIGURESEGMENTATION_EXPORT_H

#ifdef MITKPLANARFIGURESEGMENTATION_STATIC_DEFINE
#  define MITKPLANARFIGURESEGMENTATION_EXPORT
#  define MITKPLANARFIGURESEGMENTATION_NO_EXPORT
#else
#  ifndef MITKPLANARFIGURESEGMENTATION_EXPORT
#    ifdef MitkPlanarFigureSegmentation_EXPORTS
        /* We are building this library */
#      define MITKPLANARFIGURESEGMENTATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKPLANARFIGURESEGMENTATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKPLANARFIGURESEGMENTATION_NO_EXPORT
#    define MITKPLANARFIGURESEGMENTATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKPLANARFIGURESEGMENTATION_DEPRECATED
#  define MITKPLANARFIGURESEGMENTATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKPLANARFIGURESEGMENTATION_DEPRECATED_EXPORT
#  define MITKPLANARFIGURESEGMENTATION_DEPRECATED_EXPORT MITKPLANARFIGURESEGMENTATION_EXPORT MITKPLANARFIGURESEGMENTATION_DEPRECATED
#endif

#ifndef MITKPLANARFIGURESEGMENTATION_DEPRECATED_NO_EXPORT
#  define MITKPLANARFIGURESEGMENTATION_DEPRECATED_NO_EXPORT MITKPLANARFIGURESEGMENTATION_NO_EXPORT MITKPLANARFIGURESEGMENTATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKPLANARFIGURESEGMENTATION_NO_DEPRECATED
#endif

#endif
