
#ifndef MITKGRAPHALGORITHMS_EXPORT_H
#define MITKGRAPHALGORITHMS_EXPORT_H

#ifdef MITKGRAPHALGORITHMS_STATIC_DEFINE
#  define MITKGRAPHALGORITHMS_EXPORT
#  define MITKGRAPHALGORITHMS_NO_EXPORT
#else
#  ifndef MITKGRAPHALGORITHMS_EXPORT
#    ifdef MitkGraphAlgorithms_EXPORTS
        /* We are building this library */
#      define MITKGRAPHALGORITHMS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKGRAPHALGORITHMS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKGRAPHALGORITHMS_NO_EXPORT
#    define MITKGRAPHALGORITHMS_NO_EXPORT 
#  endif
#endif

#ifndef MITKGRAPHALGORITHMS_DEPRECATED
#  define MITKGRAPHALGORITHMS_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKGRAPHALGORITHMS_DEPRECATED_EXPORT
#  define MITKGRAPHALGORITHMS_DEPRECATED_EXPORT MITKGRAPHALGORITHMS_EXPORT MITKGRAPHALGORITHMS_DEPRECATED
#endif

#ifndef MITKGRAPHALGORITHMS_DEPRECATED_NO_EXPORT
#  define MITKGRAPHALGORITHMS_DEPRECATED_NO_EXPORT MITKGRAPHALGORITHMS_NO_EXPORT MITKGRAPHALGORITHMS_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKGRAPHALGORITHMS_NO_DEPRECATED
#endif

#endif
