
#ifndef MITKRIGIDREGISTRATION_EXPORT_H
#define MITKRIGIDREGISTRATION_EXPORT_H

#ifdef MITKRIGIDREGISTRATION_STATIC_DEFINE
#  define MITKRIGIDREGISTRATION_EXPORT
#  define MITKRIGIDREGISTRATION_NO_EXPORT
#else
#  ifndef MITKRIGIDREGISTRATION_EXPORT
#    ifdef MitkRigidRegistration_EXPORTS
        /* We are building this library */
#      define MITKRIGIDREGISTRATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKRIGIDREGISTRATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKRIGIDREGISTRATION_NO_EXPORT
#    define MITKRIGIDREGISTRATION_NO_EXPORT 
#  endif
#endif

#ifndef MITKRIGIDREGISTRATION_DEPRECATED
#  define MITKRIGIDREGISTRATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKRIGIDREGISTRATION_DEPRECATED_EXPORT
#  define MITKRIGIDREGISTRATION_DEPRECATED_EXPORT MITKRIGIDREGISTRATION_EXPORT MITKRIGIDREGISTRATION_DEPRECATED
#endif

#ifndef MITKRIGIDREGISTRATION_DEPRECATED_NO_EXPORT
#  define MITKRIGIDREGISTRATION_DEPRECATED_NO_EXPORT MITKRIGIDREGISTRATION_NO_EXPORT MITKRIGIDREGISTRATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKRIGIDREGISTRATION_NO_DEPRECATED
#endif

#endif
