
#ifndef MITKIMAGEDENOISING_EXPORT_H
#define MITKIMAGEDENOISING_EXPORT_H

#ifdef MITKIMAGEDENOISING_STATIC_DEFINE
#  define MITKIMAGEDENOISING_EXPORT
#  define MITKIMAGEDENOISING_NO_EXPORT
#else
#  ifndef MITKIMAGEDENOISING_EXPORT
#    ifdef MitkImageDenoising_EXPORTS
        /* We are building this library */
#      define MITKIMAGEDENOISING_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKIMAGEDENOISING_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKIMAGEDENOISING_NO_EXPORT
#    define MITKIMAGEDENOISING_NO_EXPORT 
#  endif
#endif

#ifndef MITKIMAGEDENOISING_DEPRECATED
#  define MITKIMAGEDENOISING_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKIMAGEDENOISING_DEPRECATED_EXPORT
#  define MITKIMAGEDENOISING_DEPRECATED_EXPORT MITKIMAGEDENOISING_EXPORT MITKIMAGEDENOISING_DEPRECATED
#endif

#ifndef MITKIMAGEDENOISING_DEPRECATED_NO_EXPORT
#  define MITKIMAGEDENOISING_DEPRECATED_NO_EXPORT MITKIMAGEDENOISING_NO_EXPORT MITKIMAGEDENOISING_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKIMAGEDENOISING_NO_DEPRECATED
#endif

#endif
