
#ifndef MITKMULTILABELIO_EXPORT_H
#define MITKMULTILABELIO_EXPORT_H

#ifdef MITKMULTILABELIO_STATIC_DEFINE
#  define MITKMULTILABELIO_EXPORT
#  define MITKMULTILABELIO_NO_EXPORT
#else
#  ifndef MITKMULTILABELIO_EXPORT
#    ifdef MitkMultilabelIO_EXPORTS
        /* We are building this library */
#      define MITKMULTILABELIO_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKMULTILABELIO_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKMULTILABELIO_NO_EXPORT
#    define MITKMULTILABELIO_NO_EXPORT 
#  endif
#endif

#ifndef MITKMULTILABELIO_DEPRECATED
#  define MITKMULTILABELIO_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKMULTILABELIO_DEPRECATED_EXPORT
#  define MITKMULTILABELIO_DEPRECATED_EXPORT MITKMULTILABELIO_EXPORT MITKMULTILABELIO_DEPRECATED
#endif

#ifndef MITKMULTILABELIO_DEPRECATED_NO_EXPORT
#  define MITKMULTILABELIO_DEPRECATED_NO_EXPORT MITKMULTILABELIO_NO_EXPORT MITKMULTILABELIO_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKMULTILABELIO_NO_DEPRECATED
#endif

#endif
