
#ifndef MITKDICOMREADERSERVICES_EXPORT_H
#define MITKDICOMREADERSERVICES_EXPORT_H

#ifdef MITKDICOMREADERSERVICES_STATIC_DEFINE
#  define MITKDICOMREADERSERVICES_EXPORT
#  define MITKDICOMREADERSERVICES_NO_EXPORT
#else
#  ifndef MITKDICOMREADERSERVICES_EXPORT
#    ifdef MitkDICOMReaderServices_EXPORTS
        /* We are building this library */
#      define MITKDICOMREADERSERVICES_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKDICOMREADERSERVICES_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKDICOMREADERSERVICES_NO_EXPORT
#    define MITKDICOMREADERSERVICES_NO_EXPORT 
#  endif
#endif

#ifndef MITKDICOMREADERSERVICES_DEPRECATED
#  define MITKDICOMREADERSERVICES_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKDICOMREADERSERVICES_DEPRECATED_EXPORT
#  define MITKDICOMREADERSERVICES_DEPRECATED_EXPORT MITKDICOMREADERSERVICES_EXPORT MITKDICOMREADERSERVICES_DEPRECATED
#endif

#ifndef MITKDICOMREADERSERVICES_DEPRECATED_NO_EXPORT
#  define MITKDICOMREADERSERVICES_DEPRECATED_NO_EXPORT MITKDICOMREADERSERVICES_NO_EXPORT MITKDICOMREADERSERVICES_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKDICOMREADERSERVICES_NO_DEPRECATED
#endif

#endif
