set(ITKFEM_LOADED 1)
set(ITKFEM_DEPENDS "ITKIOSpatialObjects;ITKImageFunction;ITKRegistrationCommon;ITKSpatialObjects")
set(ITKFEM_LIBRARIES "ITKFEM")
set(ITKFEM_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.7")
set(ITKFEM_LIBRARY_DIRS "")

