
#ifndef MITKOPENVIEWCORE_EXPORT_H
#define MITKOPENVIEWCORE_EXPORT_H

#ifdef MITKOPENVIEWCORE_STATIC_DEFINE
#  define MITKOPENVIEWCORE_EXPORT
#  define MITKOPENVIEWCORE_NO_EXPORT
#else
#  ifndef MITKOPENVIEWCORE_EXPORT
#    ifdef MitkOpenViewCore_EXPORTS
        /* We are building this library */
#      define MITKOPENVIEWCORE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKOPENVIEWCORE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKOPENVIEWCORE_NO_EXPORT
#    define MITKOPENVIEWCORE_NO_EXPORT 
#  endif
#endif

#ifndef MITKOPENVIEWCORE_DEPRECATED
#  define MITKOPENVIEWCORE_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKOPENVIEWCORE_DEPRECATED_EXPORT
#  define MITKOPENVIEWCORE_DEPRECATED_EXPORT MITKOPENVIEWCORE_EXPORT MITKOPENVIEWCORE_DEPRECATED
#endif

#ifndef MITKOPENVIEWCORE_DEPRECATED_NO_EXPORT
#  define MITKOPENVIEWCORE_DEPRECATED_NO_EXPORT MITKOPENVIEWCORE_NO_EXPORT MITKOPENVIEWCORE_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKOPENVIEWCORE_NO_DEPRECATED
#endif

#endif
