
#ifndef MITKCLMRUTILITIES_EXPORT_H
#define MITKCLMRUTILITIES_EXPORT_H

#ifdef MITKCLMRUTILITIES_STATIC_DEFINE
#  define MITKCLMRUTILITIES_EXPORT
#  define MITKCLMRUTILITIES_NO_EXPORT
#else
#  ifndef MITKCLMRUTILITIES_EXPORT
#    ifdef MitkCLMRUtilities_EXPORTS
        /* We are building this library */
#      define MITKCLMRUTILITIES_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKCLMRUTILITIES_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKCLMRUTILITIES_NO_EXPORT
#    define MITKCLMRUTILITIES_NO_EXPORT 
#  endif
#endif

#ifndef MITKCLMRUTILITIES_DEPRECATED
#  define MITKCLMRUTILITIES_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKCLMRUTILITIES_DEPRECATED_EXPORT
#  define MITKCLMRUTILITIES_DEPRECATED_EXPORT MITKCLMRUTILITIES_EXPORT MITKCLMRUTILITIES_DEPRECATED
#endif

#ifndef MITKCLMRUTILITIES_DEPRECATED_NO_EXPORT
#  define MITKCLMRUTILITIES_DEPRECATED_NO_EXPORT MITKCLMRUTILITIES_NO_EXPORT MITKCLMRUTILITIES_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKCLMRUTILITIES_NO_DEPRECATED
#endif

#endif
