# Generated by CMake 3.5.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget qwt)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target qwt
add_library(qwt SHARED IMPORTED)

set_target_properties(qwt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "QWT_DLL"
  INTERFACE_LINK_LIBRARIES "Qt5::Svg;Qt5::OpenGL;Qt5::PrintSupport;Qt5::Concurrent"
)

# Import target "qwt" for configuration "Debug"
set_property(TARGET qwt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(qwt PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/D/MITK-superbuild/ep/src/Qwt-build/Debug/qwtd.lib"
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/Qwt-build/Debug/qwtd.dll"
  )

# Import target "qwt" for configuration "Release"
set_property(TARGET qwt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(qwt PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/D/MITK-superbuild/ep/src/Qwt-build/Release/qwt.lib"
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/Qwt-build/Release/qwt.dll"
  )

# Import target "qwt" for configuration "MinSizeRel"
set_property(TARGET qwt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(qwt PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "E:/D/MITK-superbuild/ep/src/Qwt-build/MinSizeRel/qwt.lib"
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/Qwt-build/MinSizeRel/qwt.dll"
  )

# Import target "qwt" for configuration "RelWithDebInfo"
set_property(TARGET qwt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(qwt PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/Qwt-build/RelWithDebInfo/qwt.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/Qwt-build/RelWithDebInfo/qwt.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
