
#ifndef QTSINGLEAPPLICATION_EXPORT_H
#define QTSINGLEAPPLICATION_EXPORT_H

#ifdef QTSINGLEAPPLICATION_STATIC_DEFINE
#  define QTSINGLEAPPLICATION_EXPORT
#  define QTSINGLEAPPLICATION_NO_EXPORT
#else
#  ifndef QTSINGLEAPPLICATION_EXPORT
#    ifdef qtsingleapplication_EXPORTS
        /* We are building this library */
#      define QTSINGLEAPPLICATION_EXPORT 
#    else
        /* We are using this library */
#      define QTSINGLEAPPLICATION_EXPORT 
#    endif
#  endif

#  ifndef QTSINGLEAPPLICATION_NO_EXPORT
#    define QTSINGLEAPPLICATION_NO_EXPORT 
#  endif
#endif

#ifndef QTSINGLEAPPLICATION_DEPRECATED
#  define QTSINGLEAPPLICATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef QTSINGLEAPPLICATION_DEPRECATED_EXPORT
#  define QTSINGLEAPPLICATION_DEPRECATED_EXPORT QTSINGLEAPPLICATION_EXPORT QTSINGLEAPPLICATION_DEPRECATED
#endif

#ifndef QTSINGLEAPPLICATION_DEPRECATED_NO_EXPORT
#  define QTSINGLEAPPLICATION_DEPRECATED_NO_EXPORT QTSINGLEAPPLICATION_NO_EXPORT QTSINGLEAPPLICATION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define QTSINGLEAPPLICATION_NO_DEPRECATED
#endif

#endif
