# Generated by CMake 3.5.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtkHashSource vtkParseOGLExt vtkEncodeString)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target vtkHashSource
add_executable(vtkHashSource IMPORTED)

# Create imported target vtkParseOGLExt
add_executable(vtkParseOGLExt IMPORTED)

# Create imported target vtkEncodeString
add_executable(vtkEncodeString IMPORTED)

# Import target "vtkHashSource" for configuration "Debug"
set_property(TARGET vtkHashSource APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkHashSource PROPERTIES
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/VTK-build/bin/Debug/vtkHashSource-6.2.exe"
  )

# Import target "vtkParseOGLExt" for configuration "Debug"
set_property(TARGET vtkParseOGLExt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkParseOGLExt PROPERTIES
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/VTK-build/bin/Debug/vtkParseOGLExt-6.2.exe"
  )

# Import target "vtkEncodeString" for configuration "Debug"
set_property(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_DEBUG "E:/D/MITK-superbuild/ep/src/VTK-build/bin/Debug/vtkEncodeString-6.2.exe"
  )

# Import target "vtkHashSource" for configuration "Release"
set_property(TARGET vtkHashSource APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkHashSource PROPERTIES
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/VTK-build/bin/Release/vtkHashSource-6.2.exe"
  )

# Import target "vtkParseOGLExt" for configuration "Release"
set_property(TARGET vtkParseOGLExt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkParseOGLExt PROPERTIES
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/VTK-build/bin/Release/vtkParseOGLExt-6.2.exe"
  )

# Import target "vtkEncodeString" for configuration "Release"
set_property(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_RELEASE "E:/D/MITK-superbuild/ep/src/VTK-build/bin/Release/vtkEncodeString-6.2.exe"
  )

# Import target "vtkHashSource" for configuration "MinSizeRel"
set_property(TARGET vtkHashSource APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkHashSource PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/VTK-build/bin/MinSizeRel/vtkHashSource-6.2.exe"
  )

# Import target "vtkParseOGLExt" for configuration "MinSizeRel"
set_property(TARGET vtkParseOGLExt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkParseOGLExt PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/VTK-build/bin/MinSizeRel/vtkParseOGLExt-6.2.exe"
  )

# Import target "vtkEncodeString" for configuration "MinSizeRel"
set_property(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "E:/D/MITK-superbuild/ep/src/VTK-build/bin/MinSizeRel/vtkEncodeString-6.2.exe"
  )

# Import target "vtkHashSource" for configuration "RelWithDebInfo"
set_property(TARGET vtkHashSource APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkHashSource PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/VTK-build/bin/RelWithDebInfo/vtkHashSource-6.2.exe"
  )

# Import target "vtkParseOGLExt" for configuration "RelWithDebInfo"
set_property(TARGET vtkParseOGLExt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkParseOGLExt PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/VTK-build/bin/RelWithDebInfo/vtkParseOGLExt-6.2.exe"
  )

# Import target "vtkEncodeString" for configuration "RelWithDebInfo"
set_property(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "E:/D/MITK-superbuild/ep/src/VTK-build/bin/RelWithDebInfo/vtkEncodeString-6.2.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
