# Install script for directory: E:/D/MITK/Modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "E:/D/CMakeExternals/Install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("E:/D/MITK-superbuild/MITK-build/Modules/CppMicroServices/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Core/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/CommandLine/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/AppUtil/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DCMTesting/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/RDF/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/LegacyIO/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DataTypesExt/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Overlays/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/LegacyGL/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/AlgorithmsExt/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/MapperExt/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DICOMReader/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DICOMReaderServices/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DICOMTesting/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/SceneSerializationBase/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/PlanarFigure/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ImageDenoising/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ImageExtraction/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ImageStatistics/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/LegacyAdaptors/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/SceneSerialization/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Gizmo/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/GraphAlgorithms/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Multilabel/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ContourModel/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/SurfaceInterpolation/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Segmentation/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/PlanarFigureSegmentation/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/OpenViewCore/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/QmlItems/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/QtWidgets/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/QtWidgetsExt/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/SegmentationUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DiffusionImaging/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/GPGPU/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/OpenIGTLink/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/IGTBase/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/IGT/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/CameraCalibration/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/RigidRegistration/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/RigidRegistrationUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DeformableRegistration/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DeformableRegistrationUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/OpenCL/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/OpenCVVideoSupport/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/QtOverlays/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ToFHardware/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ToFProcessing/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/ToFUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/US/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/USUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DicomUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Simulation/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Remeshing/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Python/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/QtPython/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Persistence/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/OpenIGTLinkUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/IGTUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/VtkShaders/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/DicomRT/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/RTUI/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/IOExt/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/XNAT/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/TubeGraph/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/BiophotonicsHardware/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/Classification/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/TumorInvasionAnalysis/cmake_install.cmake")
  include("E:/D/MITK-superbuild/MITK-build/Modules/IpPicSupportIO/cmake_install.cmake")

endif()

