
#ifndef MITKCOMMANDLINE_EXPORT_H
#define MITKCOMMANDLINE_EXPORT_H

#ifdef MITKCOMMANDLINE_STATIC_DEFINE
#  define MITKCOMMANDLINE_EXPORT
#  define MITKCOMMANDLINE_NO_EXPORT
#else
#  ifndef MITKCOMMANDLINE_EXPORT
#    ifdef MitkCommandLine_EXPORTS
        /* We are building this library */
#      define MITKCOMMANDLINE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKCOMMANDLINE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKCOMMANDLINE_NO_EXPORT
#    define MITKCOMMANDLINE_NO_EXPORT 
#  endif
#endif

#ifndef MITKCOMMANDLINE_DEPRECATED
#  define MITKCOMMANDLINE_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKCOMMANDLINE_DEPRECATED_EXPORT
#  define MITKCOMMANDLINE_DEPRECATED_EXPORT MITKCOMMANDLINE_EXPORT MITKCOMMANDLINE_DEPRECATED
#endif

#ifndef MITKCOMMANDLINE_DEPRECATED_NO_EXPORT
#  define MITKCOMMANDLINE_DEPRECATED_NO_EXPORT MITKCOMMANDLINE_NO_EXPORT MITKCOMMANDLINE_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKCOMMANDLINE_NO_DEPRECATED
#endif

#endif
