
#ifndef MITKIPPICSUPPORTIO_EXPORT_H
#define MITKIPPICSUPPORTIO_EXPORT_H

#ifdef MITKIPPICSUPPORTIO_STATIC_DEFINE
#  define MITKIPPICSUPPORTIO_EXPORT
#  define MITKIPPICSUPPORTIO_NO_EXPORT
#else
#  ifndef MITKIPPICSUPPORTIO_EXPORT
#    ifdef MitkIpPicSupportIO_EXPORTS
        /* We are building this library */
#      define MITKIPPICSUPPORTIO_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKIPPICSUPPORTIO_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKIPPICSUPPORTIO_NO_EXPORT
#    define MITKIPPICSUPPORTIO_NO_EXPORT 
#  endif
#endif

#ifndef MITKIPPICSUPPORTIO_DEPRECATED
#  define MITKIPPICSUPPORTIO_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKIPPICSUPPORTIO_DEPRECATED_EXPORT
#  define MITKIPPICSUPPORTIO_DEPRECATED_EXPORT MITKIPPICSUPPORTIO_EXPORT MITKIPPICSUPPORTIO_DEPRECATED
#endif

#ifndef MITKIPPICSUPPORTIO_DEPRECATED_NO_EXPORT
#  define MITKIPPICSUPPORTIO_DEPRECATED_NO_EXPORT MITKIPPICSUPPORTIO_NO_EXPORT MITKIPPICSUPPORTIO_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKIPPICSUPPORTIO_NO_DEPRECATED
#endif

#endif
