
#ifndef MITKIMAGEEXTRACTION_EXPORT_H
#define MITKIMAGEEXTRACTION_EXPORT_H

#ifdef MITKIMAGEEXTRACTION_STATIC_DEFINE
#  define MITKIMAGEEXTRACTION_EXPORT
#  define MITKIMAGEEXTRACTION_NO_EXPORT
#else
#  ifndef MITKIMAGEEXTRACTION_EXPORT
#    ifdef MitkImageExtraction_EXPORTS
        /* We are building this library */
#      define MITKIMAGEEXTRACTION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define MITKIMAGEEXTRACTION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef MITKIMAGEEXTRACTION_NO_EXPORT
#    define MITKIMAGEEXTRACTION_NO_EXPORT 
#  endif
#endif

#ifndef MITKIMAGEEXTRACTION_DEPRECATED
#  define MITKIMAGEEXTRACTION_DEPRECATED __declspec(deprecated)
#endif

#ifndef MITKIMAGEEXTRACTION_DEPRECATED_EXPORT
#  define MITKIMAGEEXTRACTION_DEPRECATED_EXPORT MITKIMAGEEXTRACTION_EXPORT MITKIMAGEEXTRACTION_DEPRECATED
#endif

#ifndef MITKIMAGEEXTRACTION_DEPRECATED_NO_EXPORT
#  define MITKIMAGEEXTRACTION_DEPRECATED_NO_EXPORT MITKIMAGEEXTRACTION_NO_EXPORT MITKIMAGEEXTRACTION_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define MITKIMAGEEXTRACTION_NO_DEPRECATED
#endif

#endif
